version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  ignore:
    - dependency-name: '*'
      update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 10
  reviewers:
    - rpvsilva
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  ignore:
    - dependency-name: '*'
      update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 10
  reviewers:
    - rpvsilva